development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: altria_development
  pool: 20
  username: root
  password:
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: altria_test
  pool: 5
  username: root
  password:
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: altria_production
  pool: 20
  username: root
  password:
  host: localhost
